version: '3.5'

services:

  ravendb.data:
    image: ravendb/ravendb
    ports:
      - "5200:8080"
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_RunInMemory=true
    networks:
      - backend
    container_name: ravendb.data
    
networks:
  backend:
    name: ravendb-testing-backend-network
